# Generated by Django 4.1.3 on 2025-07-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('bg', 'Bulgarian')], default='en', max_length=2),
        ),
    ]
